num1=float(input("enter first number:"))
num2=float(input("enter second number:"))
print("Addition:",num1,"+",num2,"=",num1+num2)
print("Multiplication:",num1,"*",num2,"=",num1*num2)
print("Divison:",num1,"/",num2,"=",num1/num2)
print("Subtraction:",num1,"-",num2,"=",num1-num2)